### ISSUE TITLE
work for mobile

### ISSUE THREAD

**Issue by Edkroket** [khromov/sitemap-cache-warmer#20]
No really an issue but I couldn't find a Q&A part but I have it running on my website but I wonder does it also warm for mobile usage?

Thanks for this nice work anyway.
Regards Ed

**Comment by khromov** [comment]
Hi Ed,

Thanks for your question. It'd depend on whether you use responsive design (in which case it should work fine since both mobile and desktop users get the same site) or if you have special logic that determines whether the user is a mobile or desktop users based on eg. a User Agent (in which case it wouldn't work out of the box as the crawler would probably always be identified as a desktop user).

**Comment by Edkroket** [comment]
Hi goodmorning,

Thanks for the quick reply. I asked because of course my website has responsive view also. Pagespeed give different value for desktop and mobile. Desktop is just fine but mobile is too slow according to pagespeed.
How can we change the script to act as a mobile user? I would like to have that.

If not posible then thanks anyway.
